[target.aarch64-linux-android]
linker = "C:\\Users\\khong\\Documents\\android-ndk-r27d\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android29-clang.cmd"

[target.x86_64-linux-android]
linker = "C:\\Users\\khong\\Documents\\android-ndk-r27d\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\x86_64-linux-android29-clang.cmd"
